// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: apps/resource/service.proto

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vendor int32

const (
	Vendor_ALIYUN  Vendor = 0
	Vendor_TENCENT Vendor = 1
	Vendor_HUAWEI  Vendor = 2
	Vendor_VSPHERE Vendor = 3
	Vendor_AMAZON  Vendor = 4
)

// Enum value maps for Vendor.
var (
	Vendor_name = map[int32]string{
		0: "ALIYUN",
		1: "TENCENT",
		2: "HUAWEI",
		3: "VSPHERE",
		4: "AMAZON",
	}
	Vendor_value = map[string]int32{
		"ALIYUN":  0,
		"TENCENT": 1,
		"HUAWEI":  2,
		"VSPHERE": 3,
		"AMAZON":  4,
	}
)

func (x Vendor) Enum() *Vendor {
	p := new(Vendor)
	*p = x
	return p
}

func (x Vendor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vendor) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_resource_service_proto_enumTypes[0].Descriptor()
}

func (Vendor) Type() protoreflect.EnumType {
	return &file_apps_resource_service_proto_enumTypes[0]
}

func (x Vendor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vendor.Descriptor instead.
func (Vendor) EnumDescriptor() ([]byte, []int) {
	return file_apps_resource_service_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_HOST   Type = 0
	Type_RDS    Type = 1
	Type_REDIS  Type = 2
	Type_BUCKET Type = 3
	Type_DISK   Type = 4
	Type_LB     Type = 5
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "HOST",
		1: "RDS",
		2: "REDIS",
		3: "BUCKET",
		4: "DISK",
		5: "LB",
	}
	Type_value = map[string]int32{
		"HOST":   0,
		"RDS":    1,
		"REDIS":  2,
		"BUCKET": 3,
		"DISK":   4,
		"LB":     5,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_resource_service_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_apps_resource_service_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_apps_resource_service_proto_rawDescGZIP(), []int{1}
}

type SearchRequestSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int64                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber    int64                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	Keywords      string                 `protobuf:"bytes,3,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Type          *Type                  `protobuf:"varint,4,opt,name=type,proto3,enum=g17.apps.resources.pb.Type,oneof" json:"type,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequestSet) Reset() {
	*x = SearchRequestSet{}
	mi := &file_apps_resource_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequestSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequestSet) ProtoMessage() {}

func (x *SearchRequestSet) ProtoReflect() protoreflect.Message {
	mi := &file_apps_resource_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequestSet.ProtoReflect.Descriptor instead.
func (*SearchRequestSet) Descriptor() ([]byte, []int) {
	return file_apps_resource_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequestSet) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRequestSet) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *SearchRequestSet) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *SearchRequestSet) GetType() Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Type_HOST
}

func (x *SearchRequestSet) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ResourceSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*Resource            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSet) Reset() {
	*x = ResourceSet{}
	mi := &file_apps_resource_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSet) ProtoMessage() {}

func (x *ResourceSet) ProtoReflect() protoreflect.Message {
	mi := &file_apps_resource_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSet.ProtoReflect.Descriptor instead.
func (*ResourceSet) Descriptor() ([]byte, []int) {
	return file_apps_resource_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceSet) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ResourceSet) GetItems() []*Resource {
	if x != nil {
		return x.Items
	}
	return nil
}

type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: bson:"inline"
	Meta *Meta `protobuf:"bytes,1,opt,name=Meta,proto3" json:"Meta,omitempty" bson:"inline"`
	// @inject_tag: bson:"inline"
	Spec *Spec `protobuf:"bytes,2,opt,name=Spec,proto3" json:"Spec,omitempty" bson:"inline"`
	// @inject_tag: bson:"inline"
	Status        *Status `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty" bson:"inline"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_apps_resource_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_apps_resource_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_apps_resource_service_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Resource) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Meta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id" validate:"required"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" validate:"required"`
	// 通常指的是在哪个账号，用于区分不同公司的用户资源
	// @inject_tag: json:"domain" validate:"required"
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain" validate:"required"`
	// @inject_tag: json:"namespace" validate:"required"
	Namespace     string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace" validate:"required"`
	Env           string `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	CreateAt      int64  `protobuf:"varint,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	DeleteAt      int64  `protobuf:"varint,6,opt,name=delete_at,json=deleteAt,proto3" json:"delete_at,omitempty"`
	DeleteBy      string `protobuf:"bytes,7,opt,name=delete_by,json=deleteBy,proto3" json:"delete_by,omitempty"`
	SyncAt        int64  `protobuf:"varint,8,opt,name=sync_at,json=syncAt,proto3" json:"sync_at,omitempty"`
	SyncBy        string `protobuf:"bytes,9,opt,name=sync_by,json=syncBy,proto3" json:"sync_by,omitempty"`
	CredentialId  string `protobuf:"bytes,10,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	SerialNumber  string `protobuf:"bytes,11,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_apps_resource_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_apps_resource_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_apps_resource_service_proto_rawDescGZIP(), []int{3}
}

func (x *Meta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Meta) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Meta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Meta) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Meta) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Meta) GetDeleteAt() int64 {
	if x != nil {
		return x.DeleteAt
	}
	return 0
}

func (x *Meta) GetDeleteBy() string {
	if x != nil {
		return x.DeleteBy
	}
	return ""
}

func (x *Meta) GetSyncAt() int64 {
	if x != nil {
		return x.SyncAt
	}
	return 0
}

func (x *Meta) GetSyncBy() string {
	if x != nil {
		return x.SyncBy
	}
	return ""
}

func (x *Meta) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *Meta) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"vendor"
	Vendor        Vendor            `protobuf:"varint,1,opt,name=vendor,proto3,enum=g17.apps.resources.pb.Vendor" json:"vendor"`
	ResourceType  Type              `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=g17.apps.resources.pb.Type" json:"resource_type,omitempty"`
	Region        string            `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string            `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Owner         string            `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string            `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Category      string            `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Type          string            `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Description   string            `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	ExpireAt      int64             `protobuf:"varint,10,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Cpu           int64             `protobuf:"varint,11,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu           int64             `protobuf:"varint,12,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Memory        int64             `protobuf:"varint,13,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int64             `protobuf:"varint,14,opt,name=storage,proto3" json:"storage,omitempty"`
	Bandwidth     int32             `protobuf:"varint,15,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Tags          map[string]string `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Extra         map[string]string `protobuf:"bytes,18,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_apps_resource_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_apps_resource_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_apps_resource_service_proto_rawDescGZIP(), []int{4}
}

func (x *Spec) GetVendor() Vendor {
	if x != nil {
		return x.Vendor
	}
	return Vendor_ALIYUN
}

func (x *Spec) GetResourceType() Type {
	if x != nil {
		return x.ResourceType
	}
	return Type_HOST
}

func (x *Spec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Spec) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Spec) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Spec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Spec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Spec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Spec) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *Spec) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Spec) GetGpu() int64 {
	if x != nil {
		return x.Gpu
	}
	return 0
}

func (x *Spec) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Spec) GetStorage() int64 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *Spec) GetBandwidth() int32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *Spec) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Spec) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Status struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Phase          string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Describe       string                 `protobuf:"bytes,2,opt,name=describe,proto3" json:"describe,omitempty"`
	LockMode       string                 `protobuf:"bytes,3,opt,name=lock_mode,json=lockMode,proto3" json:"lock_mode,omitempty"`
	LockReason     string                 `protobuf:"bytes,4,opt,name=lock_reason,json=lockReason,proto3" json:"lock_reason,omitempty"`
	PublicAddress  []string               `protobuf:"bytes,5,rep,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"`
	PrivateAddress []string               `protobuf:"bytes,6,rep,name=private_address,json=privateAddress,proto3" json:"private_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_apps_resource_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_apps_resource_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_apps_resource_service_proto_rawDescGZIP(), []int{5}
}

func (x *Status) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Status) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *Status) GetLockMode() string {
	if x != nil {
		return x.LockMode
	}
	return ""
}

func (x *Status) GetLockReason() string {
	if x != nil {
		return x.LockReason
	}
	return ""
}

func (x *Status) GetPublicAddress() []string {
	if x != nil {
		return x.PublicAddress
	}
	return nil
}

func (x *Status) GetPrivateAddress() []string {
	if x != nil {
		return x.PrivateAddress
	}
	return nil
}

var File_apps_resource_service_proto protoreflect.FileDescriptor

const file_apps_resource_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapps/resource/service.proto\x12\x15g17.apps.resources.pb\"\xab\x02\n" +
	"\x10SearchRequestSet\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x03R\bpageSize\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x03R\n" +
	"pageNumber\x12\x1a\n" +
	"\bkeywords\x18\x03 \x01(\tR\bkeywords\x124\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.g17.apps.resources.pb.TypeH\x00R\x04type\x88\x01\x01\x12E\n" +
	"\x04tags\x18\x05 \x03(\v21.g17.apps.resources.pb.SearchRequestSet.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_type\"Z\n" +
	"\vResourceSet\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x125\n" +
	"\x05items\x18\x02 \x03(\v2\x1f.g17.apps.resources.pb.ResourceR\x05items\"\xa3\x01\n" +
	"\bResource\x12/\n" +
	"\x04Meta\x18\x01 \x01(\v2\x1b.g17.apps.resources.pb.MetaR\x04Meta\x12/\n" +
	"\x04Spec\x18\x02 \x01(\v2\x1b.g17.apps.resources.pb.SpecR\x04Spec\x125\n" +
	"\x06Status\x18\x03 \x01(\v2\x1d.g17.apps.resources.pb.StatusR\x06Status\"\xb1\x02\n" +
	"\x04Meta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\x12\x1b\n" +
	"\tcreate_at\x18\x05 \x01(\x03R\bcreateAt\x12\x1b\n" +
	"\tdelete_at\x18\x06 \x01(\x03R\bdeleteAt\x12\x1b\n" +
	"\tdelete_by\x18\a \x01(\tR\bdeleteBy\x12\x17\n" +
	"\async_at\x18\b \x01(\x03R\x06syncAt\x12\x17\n" +
	"\async_by\x18\t \x01(\tR\x06syncBy\x12#\n" +
	"\rcredential_id\x18\n" +
	" \x01(\tR\fcredentialId\x12#\n" +
	"\rserial_number\x18\v \x01(\tR\fserialNumber\"\xa4\x05\n" +
	"\x04Spec\x125\n" +
	"\x06vendor\x18\x01 \x01(\x0e2\x1d.g17.apps.resources.pb.VendorR\x06vendor\x12@\n" +
	"\rresource_type\x18\x02 \x01(\x0e2\x1b.g17.apps.resources.pb.TypeR\fresourceType\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1b\n" +
	"\texpire_at\x18\n" +
	" \x01(\x03R\bexpireAt\x12\x10\n" +
	"\x03cpu\x18\v \x01(\x03R\x03cpu\x12\x10\n" +
	"\x03gpu\x18\f \x01(\x03R\x03gpu\x12\x16\n" +
	"\x06memory\x18\r \x01(\x03R\x06memory\x12\x18\n" +
	"\astorage\x18\x0e \x01(\x03R\astorage\x12\x1c\n" +
	"\tbandwidth\x18\x0f \x01(\x05R\tbandwidth\x129\n" +
	"\x04tags\x18\x11 \x03(\v2%.g17.apps.resources.pb.Spec.TagsEntryR\x04tags\x12<\n" +
	"\x05extra\x18\x12 \x03(\v2&.g17.apps.resources.pb.Spec.ExtraEntryR\x05extra\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x01\n" +
	"\x06Status\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1a\n" +
	"\bdescribe\x18\x02 \x01(\tR\bdescribe\x12\x1b\n" +
	"\tlock_mode\x18\x03 \x01(\tR\blockMode\x12\x1f\n" +
	"\vlock_reason\x18\x04 \x01(\tR\n" +
	"lockReason\x12%\n" +
	"\x0epublic_address\x18\x05 \x03(\tR\rpublicAddress\x12'\n" +
	"\x0fprivate_address\x18\x06 \x03(\tR\x0eprivateAddress*F\n" +
	"\x06Vendor\x12\n" +
	"\n" +
	"\x06ALIYUN\x10\x00\x12\v\n" +
	"\aTENCENT\x10\x01\x12\n" +
	"\n" +
	"\x06HUAWEI\x10\x02\x12\v\n" +
	"\aVSPHERE\x10\x03\x12\n" +
	"\n" +
	"\x06AMAZON\x10\x04*B\n" +
	"\x04Type\x12\b\n" +
	"\x04HOST\x10\x00\x12\a\n" +
	"\x03RDS\x10\x01\x12\t\n" +
	"\x05REDIS\x10\x02\x12\n" +
	"\n" +
	"\x06BUCKET\x10\x03\x12\b\n" +
	"\x04DISK\x10\x04\x12\x06\n" +
	"\x02LB\x10\x052\xa6\x01\n" +
	"\x03Rpc\x12U\n" +
	"\x06Search\x12'.g17.apps.resources.pb.SearchRequestSet\x1a\".g17.apps.resources.pb.ResourceSet\x12H\n" +
	"\x04Save\x12\x1f.g17.apps.resources.pb.Resource\x1a\x1f.g17.apps.resources.pb.ResourceB\x14Z\x12cmdb/apps/resourceb\x06proto3"

var (
	file_apps_resource_service_proto_rawDescOnce sync.Once
	file_apps_resource_service_proto_rawDescData []byte
)

func file_apps_resource_service_proto_rawDescGZIP() []byte {
	file_apps_resource_service_proto_rawDescOnce.Do(func() {
		file_apps_resource_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_resource_service_proto_rawDesc), len(file_apps_resource_service_proto_rawDesc)))
	})
	return file_apps_resource_service_proto_rawDescData
}

var file_apps_resource_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apps_resource_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_apps_resource_service_proto_goTypes = []any{
	(Vendor)(0),              // 0: g17.apps.resources.pb.Vendor
	(Type)(0),                // 1: g17.apps.resources.pb.Type
	(*SearchRequestSet)(nil), // 2: g17.apps.resources.pb.SearchRequestSet
	(*ResourceSet)(nil),      // 3: g17.apps.resources.pb.ResourceSet
	(*Resource)(nil),         // 4: g17.apps.resources.pb.Resource
	(*Meta)(nil),             // 5: g17.apps.resources.pb.Meta
	(*Spec)(nil),             // 6: g17.apps.resources.pb.Spec
	(*Status)(nil),           // 7: g17.apps.resources.pb.Status
	nil,                      // 8: g17.apps.resources.pb.SearchRequestSet.TagsEntry
	nil,                      // 9: g17.apps.resources.pb.Spec.TagsEntry
	nil,                      // 10: g17.apps.resources.pb.Spec.ExtraEntry
}
var file_apps_resource_service_proto_depIdxs = []int32{
	1,  // 0: g17.apps.resources.pb.SearchRequestSet.type:type_name -> g17.apps.resources.pb.Type
	8,  // 1: g17.apps.resources.pb.SearchRequestSet.tags:type_name -> g17.apps.resources.pb.SearchRequestSet.TagsEntry
	4,  // 2: g17.apps.resources.pb.ResourceSet.items:type_name -> g17.apps.resources.pb.Resource
	5,  // 3: g17.apps.resources.pb.Resource.Meta:type_name -> g17.apps.resources.pb.Meta
	6,  // 4: g17.apps.resources.pb.Resource.Spec:type_name -> g17.apps.resources.pb.Spec
	7,  // 5: g17.apps.resources.pb.Resource.Status:type_name -> g17.apps.resources.pb.Status
	0,  // 6: g17.apps.resources.pb.Spec.vendor:type_name -> g17.apps.resources.pb.Vendor
	1,  // 7: g17.apps.resources.pb.Spec.resource_type:type_name -> g17.apps.resources.pb.Type
	9,  // 8: g17.apps.resources.pb.Spec.tags:type_name -> g17.apps.resources.pb.Spec.TagsEntry
	10, // 9: g17.apps.resources.pb.Spec.extra:type_name -> g17.apps.resources.pb.Spec.ExtraEntry
	2,  // 10: g17.apps.resources.pb.Rpc.Search:input_type -> g17.apps.resources.pb.SearchRequestSet
	4,  // 11: g17.apps.resources.pb.Rpc.Save:input_type -> g17.apps.resources.pb.Resource
	3,  // 12: g17.apps.resources.pb.Rpc.Search:output_type -> g17.apps.resources.pb.ResourceSet
	4,  // 13: g17.apps.resources.pb.Rpc.Save:output_type -> g17.apps.resources.pb.Resource
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_apps_resource_service_proto_init() }
func file_apps_resource_service_proto_init() {
	if File_apps_resource_service_proto != nil {
		return
	}
	file_apps_resource_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_resource_service_proto_rawDesc), len(file_apps_resource_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_resource_service_proto_goTypes,
		DependencyIndexes: file_apps_resource_service_proto_depIdxs,
		EnumInfos:         file_apps_resource_service_proto_enumTypes,
		MessageInfos:      file_apps_resource_service_proto_msgTypes,
	}.Build()
	File_apps_resource_service_proto = out.File
	file_apps_resource_service_proto_goTypes = nil
	file_apps_resource_service_proto_depIdxs = nil
}
